### PR TITLE
resilient: feature - python3 compatibility and on-poll feature

### PR DESCRIPTION
**Pull request by bliew-splunk**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [ ] The manual_readme_content.md has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [ ] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [ ] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe):

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers),
  please document them in the `manual_readme_content.md`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `manual_readme_content.md` all methods (eg, OAuth) used to authenticate
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `manual_readme_content.md`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

## Release Notes (REQUIRED)
- Python 3 compatibility.
- Added `on_poll` action which ingests Resilient incidents and artifacts.

## What is the current behavior? (OPTIONAL)
- Current version of app uses Python 2 and does not work with latest versions of SOAR

## What is the new behavior? (OPTIONAL)
- See release notes please.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by bliew-splunk** [comment]
Hi team, I need help with getting the static tests to pass. I believe there's around 3 still failing test cases.

**Comment by dhwanis-crest** [comment]
Hi @bliew-splunk ,
We have made some changes according to our dev standards along with changes due to module vulnerabilities. We have added the directly used dependencies in the requirements.txt file. Also, the cryptography and jwcrypto modules have license and security failures due to which we have removed those from the dev-requirements.txt file as they are not used directly anywhere in the code. Could you please verify the changes and let us know in case you have any concerns?

**Comment by bliew-splunk** [comment]
> Hi @bliew-splunk , We have made some changes according to our dev standards along with changes due to module vulnerabilities. We have added the directly used dependencies in the requirements.txt file. Also, the cryptography and jwcrypto modules have license and security failures due to which we have removed those from the dev-requirements.txt file as they are not used directly anywhere in the code. Could you please verify the changes and let us know in case you have any concerns?

Hi @dhwanis-crest, what is the difference between `pip39_dependencies` and `pip_dependencies`?
Does `"input_file": "wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl"` mean it is installed from a wheel on disk? Or does this still pull from pypi?
Also, after making these changes were you able to package the app and test it?

**Comment by bliew-splunk** [comment]
@dhwanis-crest  - I got this error when trying to install the app. I think the issue is referencing the wheel file that does not exist on disk. Can we not just install from Pypi?
```
{
  "log_type": "django",
  "component": "webserver",
  "product_version": "6.2.0.355",
  "time": "2024-03-04T07:27:39.710436",
  "logger": "app_install",
  "pid": 95709,
  "level": "ERROR",
  "file": "/opt/phantom/www/phantom_ui/phapps/installer.py",
  "line": 1065,
  "message": "Error importing app by user: Installation of wheel modules failed for app b108b9d0-4611-4abf-af34-4334e084031f. Exception: Command '['/opt/phantom/bin/phenv', 'python3', '-m', 'pip', 'install', '--no-cache-dir', '--target', '/opt/phantom/apps/app_install_br86_xvj/resilient/dependencies', '--no-deps', '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl', '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/cachetools-5.3.2-py3-none-any.whl']' returned non-zero exit status 1.\nOutput: Processing /opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl\nError output: WARNING: Requirement '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl' looks like a filename, but the file does not exist\nWARNING: Requirement '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/cachetools-5.3.2-py3-none-any.whl' looks like a filename, but the file does not exist\nERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl'\n\n\n[notice] A new release of pip is available: 23.0 -> 24.0\n[notice] To update, run: pip3 install --upgrade pip",
  "ctx_request_id": "30aa1127624e9b7e8511e97a73124a46",
  "ctx_request_method": "POST",
  "ctx_user_id": 1,
  "ctx_request_remote_addr": "204.107.141.245",
  "ctx_request_user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
  "ctx_request_view": "app_install",
  "ctx_request_route": "^app_install$",
  "ctx_app_install_source": "tgz_upload",
  "ctx_app_install_is_forced": false,
  "ctx_app_id": "b108b9d0-4611-4abf-af34-4334e084031f",
  "ctx_app_package_name": "phantom_resilient",
  "ctx_app_version": "2.0.0",
  "ctx_app_min_phantom_version": "6.1.1",
  "ctx_connector_id": 188,
  "ctx_connector_name": "Resilient",
  "ctx_connector_version": "2.0.0",
  "ctx_connector_is_custom": false,
  "exc_info": [
    "Traceback (most recent call last):",
    "  File \"/opt/phantom/www/phantom_ui/phapps/installer.py\", line 611, in handle_pip_dependencies",
    "    phproc.run(pip_cmd, error_fn=_clean_pip_error, stream=False)",
    "  File \"/opt/phantom/pycommon3/phantom_common/phproc.py\", line 346, in run",
    "    proc.check_returncode()",
    "  File \"/opt/phantom/pycommon3/phantom_common/phproc.py\", line 486, in check_returncode",
    "    raise PhCalledProcessError(",
    "phantom_common.phproc.PhCalledProcessError: Command '['/opt/phantom/bin/phenv', 'python3', '-m', 'pip', 'install', '--no-cache-dir', '--target', '/opt/phantom/apps/app_install_br86_xvj/resilient/dependencies', '--no-deps', '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl', '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/cachetools-5.3.2-py3-none-any.whl']' returned non-zero exit status 1.",
    "Output: Processing /opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl",
    "Error output: WARNING: Requirement '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl' looks like a filename, but the file does not exist",
    "WARNING: Requirement '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/cachetools-5.3.2-py3-none-any.whl' looks like a filename, but the file does not exist",
    "ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl'",
    "",
    "",
    "[notice] A new release of pip is available: 23.0 -> 24.0",
    "[notice] To update, run: pip3 install --upgrade pip",
    "",
    "During handling of the above exception, another exception occurred:",
    "",
    "Traceback (most recent call last):",
    "  File \"/opt/phantom/www/phantom_ui/phapps/installer.py\", line 999, in complete_install",
    "    handle_pip_dependencies(app_json, tmp_app_dir)",
    "  File \"/opt/phantom/www/phantom_ui/phapps/installer.py\", line 613, in handle_pip_dependencies",
    "    raise PipDependencyError(",
    "phantom_ui.phapps.installer.PipDependencyError: Installation of wheel modules failed for app b108b9d0-4611-4abf-af34-4334e084031f. Exception: Command '['/opt/phantom/bin/phenv', 'python3', '-m', 'pip', 'install', '--no-cache-dir', '--target', '/opt/phantom/apps/app_install_br86_xvj/resilient/dependencies', '--no-deps', '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl', '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/cachetools-5.3.2-py3-none-any.whl']' returned non-zero exit status 1.",
    "Output: Processing /opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl",
    "Error output: WARNING: Requirement '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl' looks like a filename, but the file does not exist",
    "WARNING: Requirement '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/cachetools-5.3.2-py3-none-any.whl' looks like a filename, but the file does not exist",
    "ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl'",
    "",
    "",
    "[notice] A new release of pip is available: 23.0 -> 24.0",
    "[notice] To update, run: pip3 install --upgrade pip"
  ]
}
```

**Comment by dhwanis-crest** [comment]
This issue is occurring as folder containing all wheel files have been ignored by gitignore. I will add the necessary wheels files here.

**Comment by dhwanis-crest** [comment]
> > Hi @bliew-splunk , We have made some changes according to our dev standards along with changes due to module vulnerabilities. We have added the directly used dependencies in the requirements.txt file. Also, the cryptography and jwcrypto modules have license and security failures due to which we have removed those from the dev-requirements.txt file as they are not used directly anywhere in the code. Could you please verify the changes and let us know in case you have any concerns?
> 
> Hi @dhwanis-crest, what is the difference between `pip39_dependencies` and `pip_dependencies`? Does `"input_file": "wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl"` mean it is installed from a wheel on disk? Or does this still pull from pypi? Also, after making these changes were you able to package the app and test it?

pip_39 dependencies specifies any dependencies required for your Python 3 app. pip_dependencies is ignored, if this key is present. 
"input_file": "wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl" means that which wheel file is to be installed from the package's wheels folder.
As this is Not a Splunk supported app, we do not have an asset for this app and hence, we are unable to test it.

**Comment by dhwanis-crest** [comment]
> @dhwanis-crest - I got this error when trying to install the app. I think the issue is referencing the wheel file that does not exist on disk. Can we not just install from Pypi?
> 
> ```
> {
>   "log_type": "django",
>   "component": "webserver",
>   "product_version": "6.2.0.355",
>   "time": "2024-03-04T07:27:39.710436",
>   "logger": "app_install",
>   "pid": 95709,
>   "level": "ERROR",
>   "file": "/opt/phantom/www/phantom_ui/phapps/installer.py",
>   "line": 1065,
>   "message": "Error importing app by user: Installation of wheel modules failed for app b108b9d0-4611-4abf-af34-4334e084031f. Exception: Command '['/opt/phantom/bin/phenv', 'python3', '-m', 'pip', 'install', '--no-cache-dir', '--target', '/opt/phantom/apps/app_install_br86_xvj/resilient/dependencies', '--no-deps', '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl', '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/cachetools-5.3.2-py3-none-any.whl']' returned non-zero exit status 1.\nOutput: Processing /opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl\nError output: WARNING: Requirement '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl' looks like a filename, but the file does not exist\nWARNING: Requirement '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/cachetools-5.3.2-py3-none-any.whl' looks like a filename, but the file does not exist\nERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl'\n\n\n[notice] A new release of pip is available: 23.0 -> 24.0\n[notice] To update, run: pip3 install --upgrade pip",
>   "ctx_request_id": "30aa1127624e9b7e8511e97a73124a46",
>   "ctx_request_method": "POST",
>   "ctx_user_id": 1,
>   "ctx_request_remote_addr": "204.107.141.245",
>   "ctx_request_user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
>   "ctx_request_view": "app_install",
>   "ctx_request_route": "^app_install$",
>   "ctx_app_install_source": "tgz_upload",
>   "ctx_app_install_is_forced": false,
>   "ctx_app_id": "b108b9d0-4611-4abf-af34-4334e084031f",
>   "ctx_app_package_name": "phantom_resilient",
>   "ctx_app_version": "2.0.0",
>   "ctx_app_min_phantom_version": "6.1.1",
>   "ctx_connector_id": 188,
>   "ctx_connector_name": "Resilient",
>   "ctx_connector_version": "2.0.0",
>   "ctx_connector_is_custom": false,
>   "exc_info": [
>     "Traceback (most recent call last):",
>     "  File \"/opt/phantom/www/phantom_ui/phapps/installer.py\", line 611, in handle_pip_dependencies",
>     "    phproc.run(pip_cmd, error_fn=_clean_pip_error, stream=False)",
>     "  File \"/opt/phantom/pycommon3/phantom_common/phproc.py\", line 346, in run",
>     "    proc.check_returncode()",
>     "  File \"/opt/phantom/pycommon3/phantom_common/phproc.py\", line 486, in check_returncode",
>     "    raise PhCalledProcessError(",
>     "phantom_common.phproc.PhCalledProcessError: Command '['/opt/phantom/bin/phenv', 'python3', '-m', 'pip', 'install', '--no-cache-dir', '--target', '/opt/phantom/apps/app_install_br86_xvj/resilient/dependencies', '--no-deps', '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl', '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/cachetools-5.3.2-py3-none-any.whl']' returned non-zero exit status 1.",
>     "Output: Processing /opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl",
>     "Error output: WARNING: Requirement '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl' looks like a filename, but the file does not exist",
>     "WARNING: Requirement '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/cachetools-5.3.2-py3-none-any.whl' looks like a filename, but the file does not exist",
>     "ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl'",
>     "",
>     "",
>     "[notice] A new release of pip is available: 23.0 -> 24.0",
>     "[notice] To update, run: pip3 install --upgrade pip",
>     "",
>     "During handling of the above exception, another exception occurred:",
>     "",
>     "Traceback (most recent call last):",
>     "  File \"/opt/phantom/www/phantom_ui/phapps/installer.py\", line 999, in complete_install",
>     "    handle_pip_dependencies(app_json, tmp_app_dir)",
>     "  File \"/opt/phantom/www/phantom_ui/phapps/installer.py\", line 613, in handle_pip_dependencies",
>     "    raise PipDependencyError(",
>     "phantom_ui.phapps.installer.PipDependencyError: Installation of wheel modules failed for app b108b9d0-4611-4abf-af34-4334e084031f. Exception: Command '['/opt/phantom/bin/phenv', 'python3', '-m', 'pip', 'install', '--no-cache-dir', '--target', '/opt/phantom/apps/app_install_br86_xvj/resilient/dependencies', '--no-deps', '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl', '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/cachetools-5.3.2-py3-none-any.whl']' returned non-zero exit status 1.",
>     "Output: Processing /opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl",
>     "Error output: WARNING: Requirement '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl' looks like a filename, but the file does not exist",
>     "WARNING: Requirement '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/cachetools-5.3.2-py3-none-any.whl' looks like a filename, but the file does not exist",
>     "ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/opt/phantom/apps/app_install_br86_xvj/resilient/wheels/py3/resilient-51.0.0.0.430-py3-none-any.whl'",
>     "",
>     "",
>     "[notice] A new release of pip is available: 23.0 -> 24.0",
>     "[notice] To update, run: pip3 install --upgrade pip"
>   ]
> }
> ```

That could be done, but we generally prefer adding wheel files over Pypi as it reduces a certain amount of dependency on the internet. Also, by adding wheels, the app would be pre-packaged with all the required dependencies already present and is also faster to some extent than importing dependencies from Pypi.

**Comment by bliew-splunk** [comment]
@dhwanis-crest Sure, happy to have the wheel files embedded in the app

**Comment by dhwanis-crest** [comment]
Hi @bliew-splunk ,
Is the dev-requirements file needed?  We have added cachetools and resilient to requirements.txt file. Most of the libraries are not used directly anywhere in the code, so if not required we can delete the dev-requirements.txt file

**Comment by bliew-splunk** [comment]
@

> Hi @bliew-splunk , Is the dev-requirements file needed? We have added cachetools and resilient to requirements.txt file. Most of the libraries are not used directly anywhere in the code, so if not required we can delete the dev-requirements.txt file
@dhwanis-crest You can remove dev-requirements.txt, thanks

**Comment by dhwanis-crest** [comment]
Hi @bliew-splunk ,
We have modified the contains for "vault_id" parameter in "add_attachment" action, based on the contains mentioned for this parameter in the output datapaths, as the contains for both were different. Please let us know if this change is fine and check if it doesn't affect any of your playbooks.

**Comment by bliew-splunk** [comment]
> Hi @bliew-splunk , We have modified the contains for "vault_id" parameter in "add_attachment" action, based on the contains mentioned for this parameter in the output datapaths, as the contains for both were different. Please let us know if this change is fine and check if it doesn't affect any of your playbooks.

All good, thanks

**Review by mishalp-crest — APPROVED** [review]

**Review by achandya-crest — APPROVED** [review]

**Review by ishans-crest — APPROVED** [review]

**Pull request merged**
